{% set version = "2.3.4" %}

package:
  name: bob
  version: {{ version }}

source:
  fn: bob-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob/bob-{{ version }}.zip
  md5: 1b9fdf0c02b412b99217ce557073ff4b

build:
  number: 0
  skip: true  # [win]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - bob.extension ==2.2.1
    - bob.blitz ==2.0.9
    - bob.core ==2.1.3
    - bob.io.base ==2.0.10
    - bob.sp ==2.0.5
    - bob.ap ==2.0.5
    - bob.math ==2.0.4
    - bob.measure ==2.1.2
    - bob.db.base ==2.0.6
    - bob.io.audio ==2.0.1
    - bob.io.image ==2.1.1
    - bob.io.video ==2.0.10
    - bob.io.matlab ==2.0.5
    - bob.ip.base ==2.0.10
    - bob.ip.color ==2.0.5
    - bob.ip.draw ==2.0.4
    - bob.ip.gabor ==2.0.5
    - bob.learn.activation ==2.0.5
    - bob.learn.libsvm ==2.0.6
    - bob.learn.linear ==2.0.8
    - bob.learn.mlp ==2.1
    - bob.learn.em ==2.0.9
    - bob.learn.boosting ==2.0.7
    - bob.db.verification.utils ==2.0.8
    - bob.db.iris ==2.0.4
    - bob.db.wine ==2.0.4
    - bob.db.mnist ==2.0.4
    - bob.db.atnt ==2.0.4
    - bob.ip.facedetect ==2.0.8
    - bob.ip.optflow.hornschunck ==2.0.7
    - bob.ip.optflow.liu ==2.0.6

  run:
    - python
    - bob.extension ==2.2.1
    - bob.blitz ==2.0.9
    - bob.core ==2.1.3
    - bob.io.base ==2.0.10
    - bob.sp ==2.0.5
    - bob.ap ==2.0.5
    - bob.math ==2.0.4
    - bob.measure ==2.1.2
    - bob.db.base ==2.0.6
    - bob.io.audio ==2.0.1
    - bob.io.image ==2.1.1
    - bob.io.video ==2.0.10
    - bob.io.matlab ==2.0.5
    - bob.ip.base ==2.0.10
    - bob.ip.color ==2.0.5
    - bob.ip.draw ==2.0.4
    - bob.ip.gabor ==2.0.5
    - bob.learn.activation ==2.0.5
    - bob.learn.libsvm ==2.0.6
    - bob.learn.linear ==2.0.8
    - bob.learn.mlp ==2.1
    - bob.learn.em ==2.0.9
    - bob.learn.boosting ==2.0.7
    - bob.db.verification.utils ==2.0.8
    - bob.db.iris ==2.0.4
    - bob.db.wine ==2.0.4
    - bob.db.mnist ==2.0.4
    - bob.db.atnt ==2.0.4
    - bob.ip.facedetect ==2.0.8
    - bob.ip.optflow.hornschunck ==2.0.7
    - bob.ip.optflow.liu ==2.0.6

test:
  imports:
    - bob
    - bob.script
    - bob.test

  commands:
    - nosetests -sv bob --exclude=test_cpp_interface  # [not osx]
    - CFLAGS="${CFLAGS} -pthread" LDFLAGS="${LDFLAGS} -lpthread" DYLD_FALLBACK_LIBRARY_PATH=$PREFIX/lib nosetests -sv bob.extension --exclude=test_cpp_interface  # [osx]

  requires:
    - nose
    - cmake
    - pkg-config
    - freetype

about:
  home: http://idiap.github.io/bob/
  license: Modified BSD License (3-clause)
  summary: Bob is a free signal-processing and machine learning toolbox originally developed by the Biometrics group at Idiap Research Institute, in Switzerland.

extra:
  recipe-maintainers:
    - 183amir
